### ISSUE TITLE
Building freeze for Ubuntu

### ISSUE THREAD

**Issue by todpole3** [rusty1s/pytorch_unique#1]
I'm on Ubuntu and simply running `pip install cffi torch-unique` leaves an empty stdout for a very long time such that I have to manually kill the `pip`.

The I tried to run `build.sh` directly from the source repo, the following building statement again halts for a long time with nothing on stdout:
```
nvcc -c -o $BUILD_DIR/kernel.so $SRC_DIR/kernel.cu -arch=sm_35 -Xcompiler -fPIC -shared -I$TORCH/lib/include/TH -I$TORCH/lib/include/THC -I$SRC_DIR
```
Eventually, I have to manually stop the kernel compilation. 

My `nvcc --version` output:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

Any idea on what might be going on?

**Comment by rusty1s** [comment]
Hello,

sadly no, I don't know exactly what's going on yet. Compilation can take up to one minute on my machine (thrust include slows this process down). However, I tested compilation on macOS and Ubuntu and both worked fine, so I'm really sorry to hear that your build freezes. I will investigate it further. Can you post the `--verbose` output of the `nvcc` command?

**Comment by todpole3** [comment]
My `nvcc --verbose` output:

```
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : No input files specified; use option --help for more information
```

**Comment by todpole3** [comment]
Thanks for the `--verbose` tip! Problem got solved.

For some reason, my machine is going slow and I was being impatient. It took minutes for the `pip install` to finish but I'm able to import the library now.

**Comment by rusty1s** [comment]
Glad that it's working now. However, I will try to make the installation process faster.
