### ISSUE TITLE
compatable with pytorch 1.0.0?

### ISSUE THREAD

**Issue by fuxianh** [rusty1s/pytorch_unique#10]
I cannot install torch-unique with pip, it just give me 2 errors:
 

cuda/unique_kernel.cu(22): error: no suitable user-defined conversion from "at::Type" to "c10::IntList" exists

  cuda/unique_kernel.cu(22): error: no instance of constructor "at::TensorOptions::TensorOptions" matches the argument list
              argument types are: (int64_t)

  2 errors detected in the compilation of "/tmp/tmpxft_00007f15_00000000-6_unique_kernel.cpp1.ii".
  error: command '/home/xx/cuda-9.0/bin/nvcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for torch-unique
  Running setup.py clean for torch-unique
Failed to build torch-unique

**Comment by rusty1s** [comment]
This package does not work with PyTorch 1.0. PyTorch >= 0.4.1 now comes with its own [unique CUDA implementation](https://pytorch.org/docs/master/tensors.html#torch.Tensor.unique).
