### ISSUE TITLE
Failed when setup torch_unique

### ISSUE THREAD

**Issue by qinchuanhui** [rusty1s/pytorch_unique#12]
I am restricted to use torch 1.1.0  with cuda 10.0 . And I can successfully import torch_geometric
However, when I try to run my code, I still have to install torch_unique, then I got the error:

 Building wheel for torch-unique (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/miniconda3/envs/myconda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-61f1l09m/torch-unique/setup.py'"'"'; __file__='"'"'/tmp/pip-install-61f1l09m/torch-unique/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7k15lsxw
       cwd: /tmp/pip-install-61f1l09m/torch-unique/
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_unique.py -> build/lib.linux-x86_64-3.6/test
    copying test/utils.py -> build/lib.linux-x86_64-3.6/test
    creating build/lib.linux-x86_64-3.6/torch_unique
    copying torch_unique/__init__.py -> build/lib.linux-x86_64-3.6/torch_unique
    copying torch_unique/unique.py -> build/lib.linux-x86_64-3.6/torch_unique
    running build_ext
    building 'torch_unique.unique_cuda' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cuda
    gcc -pthread -B /root/miniconda3/envs/myconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include -I/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include/TH -I/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/miniconda3/envs/myconda/include/python3.6m -c cuda/unique.cpp -o build/temp.linux-x86_64-3.6/cuda/unique.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=unique_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from cuda/unique.cpp:1:0:
    /root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
     #warning \
      ^~~~~~~
    /usr/local/cuda/bin/nvcc -I/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include -I/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include/TH -I/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/miniconda3/envs/myconda/include/python3.6m -c cuda/unique_kernel.cu -o build/temp.linux-x86_64-3.6/cuda/unique_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=unique_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    **cuda/unique_kernel.cu(22): error: no suitable user-defined conversion from "at::DeprecatedTypeProperties" to "c10::IntArrayRef" exists
 cuda/unique_kernel.cu(22): error: no instance of constructor "c10::TensorOptions::TensorOptions" matches the argument list
                argument types are: (int64_t)**
    **2 errors detected in the compilation of "/tmp/tmpxft_0000006e_00000000-6_unique_kernel.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1**
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/miniconda3/envs/myconda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-61f1l09m/torch-unique/setup.py'"'"'; __file__='"'"'/tmp/pip-install-61f1l09m/torch-unique/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vbyz7xzm/install-record.txt --single-version-externally-managed --compile --install-headers /root/miniconda3/envs/myconda/include/python3.6m/torch-unique Check the logs for full command output.

Can you help me

**Comment by rusty1s** [comment]
No need to install this package with `torch==1.1.0`, since PyTorch comes with its own `unique` implementation since 0.4.1. Which PyTorch Geometric are you using?

**Comment by qinchuanhui** [comment]
My question has been solved by changing the version, thanks a lot.
