### ISSUE TITLE
Compilation issue with CUDA 9.1 and GCC 6

### ISSUE THREAD

**Issue by mbahri** [rusty1s/pytorch_unique#4]
Hello

pytorch_unique does not compile on Ubuntu 18.04 with CUDA 9.1 and GCC 6.

Setup:

- Ubuntu 18.04
- CUDA installed via `sudo apt install nvidia-cuda-toolkit`

```
$ gcc --version
gcc (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
```

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```
Pytorch 0.4.0 installed for CUDA 9.1 via pip:

```
pip install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
pip install torchvision
```

All other dependencies of pytorch-geometric installed successfully.

Error log attached.
[pytorch_unique_cuda91_gcc6_build_error.log](https://github.com/rusty1s/pytorch_unique/files/2041572/pytorch_unique_cuda91_gcc6_build_error.log)

Best
Mehdi

**Comment by rusty1s** [comment]
See #3.
