### ISSUE TITLE
Add option to build CUDA extensions

### ISSUE THREAD

**Issue by fiskio** [rusty1s/pytorch_unique#6]
I am currently building the docker image of my project during CI on a runner with no GPU.   
At the moment the CUDA extensions are not built as `torch.cuda.is_available()` returns False.  
I would like to pass a flag at install time, or set a env var, so that compilation is forced and I can build on CPU but run on GPU.

**Comment by rusty1s** [comment]
Hi,

I’m sorry if I don‘t understand your problem, but the CUDA extensions can‘t be built if CUDA is not available. Why would you try to compile them anyway?

**Comment by rusty1s** [comment]
Closed due to inactivity.

**Comment by NarekA** [comment]
Just wanted to express that we are having the exact same issue, and would really appreciate this feature.

**Comment by rusty1s** [comment]
Do you still need this package? In case, I could implement the suggestions from [here](https://github.com/rusty1s/pytorch_scatter/issues/12).

**Comment by rusty1s** [comment]
Fixed in 1.0.3
